# Copyright 2023 Antoine Aubry, Catarina Tavares
# 
# This file is part of GlutenFreeMap.
# 
# GlutenFreeMap is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# 
# GlutenFreeMap is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with GlutenFreeMap.
# If not, see <https://www.gnu.org/licenses/>.

title: GlutenFreeMap
email: glutenfreemap@aaubry.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://glutenfreemap.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  glutenfreemap

languages:
- id: pt
  name: Português
  info:
    description:
      Encontre restaurantes, pastelarias, gelatarias, hotéis, etc. sem glúten adequados para celíacos em Portugal.
  install:
    title: Instalar Aplicação
    description:
      Adicione esta aplicação ao seu ecrã inicial para que esteja sempre acessível.
    accept: Instalar
    cancel: Não obrigado
  links:
    map: Mapa
    about: Acerca
    contacts: Reportar problemas
    language: Língua
  new_changes:
    title: Atualizações
    description: A aplicação foi atualizada. Deseja ver as novidades?
    accept: Sim
    cancel: Não obrigado
  changelog:
    last_update: Última atualização em %Y-%m-%d
    new_venues: "Novos estabelecimentos adicionados:"

- id: en
  name: English
  info:
    description:
      Find gluten-free restaurants, bakeries, hotels, etc. suitable for celiacs in Portugal.
  install:
    title: Install Application
    description:
      Add this app to your home screen so it's always accessible.
    accept: Install
    cancel: No thanks
  links:
    map: Map
    about: About
    contacts: Report issues
    language: Language
  new_changes:
    title: Updates
    description: The application has been updated. Do you want to see the news?
    accept: 'Yes'
    cancel: No thanks
  changelog:
    last_update: Last updated on %Y-%m-%d
    new_venues: "New venues added:"

- id: fr
  name: Français
  info:
    description:
      Trouvez des restaurants, pâtisseries, glaciers, hotels, etc. sans gluten adaptés aux aux cœliaques au Portugal.
  install:
    title: Installer l'Application
    description:
      Ajoutez cette application à votre écran d'accueil pour qu'elle soit toujours accessible.
    accept: Installer
    cancel: Non merci
  links:
    map: Carte
    about: À propos
    contacts: Signaler un problème
    language: Langue
  new_changes:
    title: Mises à jour
    description: L'application a été mise à jour. Voulez-vous voir les nouveautés ?
    accept: Oui
    cancel: Non merci
  changelog:
    last_update: Dernière mise à jour le %Y-%m-%d
    new_venues: "Nouveaux établissements ajoutés:"

- id: es
  name: Español
  info:
    description:
      Encuentra restaurantes, pastelerías, heladerias, hoteles, etc sin gluten adecuados para celíacos en Portugal.
  install:
    title: Instalar aplicación
    description:
      Agregue esta aplicación a su pantalla de inicio para que siempre esté accesible.
    accept: Instalar
    cancel: No gracias
  links:
    map: Mapa
    about: Sobre
    contacts: Reportar problemas
    language: Idioma
  new_changes:
    title: Actualizaciones
    description: La aplicación ha sido actualizada. ¿Quieres ver las novedades?
    accept: Sí
    cancel: No gracias
  changelog:
    last_update: Última actualización el %Y-%m-%d
    new_venues: "Nuevos establecimientos añadidos:"

defaults:
  - scope:
      path: "*/map.md"
      type: pages
    values:
      includeScripts: map-scripts.html
      includeCss: map-css.html
  - scope:
      path: "**/*.md"
      type: pages
    values:
      sitemap: true

collections:
  - changelog
